name: MatrixBuild

on: [push]
# nice example: https://github.com/microsoft/vs-editor-api/blob/master/.github/workflows/main.yml

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest]
    steps:
    - uses: actions/checkout@v1

    - name: Build
      run: dotnet build
    
    - name: Test
      run: dotnet test
